pipeline {
    agent {
        label 'AGENT-1'
    }
    options {
        timeout(time: 30, unit: 'MINUTES') //timeout
        disableConcurrentBuilds()  //disable concurent build one after one
        ansiColor('xterm')
    }
    parameters {
       choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'select action')
    }

    stages{
        stage('Init and Plan'){
          steps {
             withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                sh """
                    cd 70-ecr
                    terraform init -reconfigure
                    terraform plan -out=tfplan
                 """
             }
          }
        }
        stage('Apply and Destroy'){
         /* input {
            message "Should we continue to ${params.ACTION}"
            ok "Yes, we should."
          } */
          steps {
             withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                sh """
                    cd 70-ecr
                    if [ ${params.ACTION} == 'apply' ]
                    then 
                      terraform apply --auto-approve tfplan
                    elif [ ${params.ACTION} == 'destroy' ]
                    then 
                     terraform destroy --auto-approve 
                    fi
                 """
             }
          }
        }
    }

     post {
        always {
            echo 'This section always runs!'
            deleteDir() //in jenkins this function will delete the workspace directory of the job on the agent (VM/container)
        }
        success {
            echo 'This section runs when pipeline sucess'
        }
        failure {
            echo 'This section runs when pipeline failed' 
        }
    }
}