pipeline {
    agent {
        label 'AGENT-1'
    }
    options {
        timeout(time: 30, unit: 'MINUTES') //timeout
        disableConcurrentBuilds()  //disable concurent build one after one
        ansiColor('xterm')
    }
    parameters {
       choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'select action')
    }

    stages{
        stage('Init and Plan'){
          steps {
             withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                sh """
                    cd 80-alb
                    terraform init -reconfigure
                    terraform plan -out=tfplan
                 """
             }
          }
        }
        stage('Apply and Destroy'){
         /* input {
            message "Should we continue to ${params.ACTION}"
            ok "Yes, we should."
          } */
          steps {
             withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                sh """
                    cd 80-alb
                    if [ ${params.ACTION} == 'apply' ]
                    then 
                      terraform apply --auto-approve tfplan
                    fi
                 """
             }
          }
        }
        stage('Destroy'){
            when {
                expression { params.ACTION == 'destroy' }
            }
            steps{
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    script {
                        def directories = ['80-alb', '70-ecr', '60-acm', '50-eks', '30-bastion', '20-sg', '10-vpc']
                        for (dir in directories) {
                            echo "Destroying resources in directory: ${dir}"
                            sh """
                            cd ${dir}
                            terraform init -reconfigure
                            terraform destroy -auto-approve || { echo "Failed to destroy resources in ${dir}"; exit 1; }
                            cd ..
                            """
                        }
                    }
                }
            }
        }
    }

     post {
        always {
            echo 'This section always runs!'
            deleteDir() //in jenkins this function will delete the workspace directory of the job on the agent (VM/container)
        }
        success {
            echo 'This section runs when pipeline sucess'
        }
        failure {
            echo 'This section runs when pipeline failed' 
        }
    }
}